ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RECHARGE_SUCCEEDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RECHARGE_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RECHARGE_REFUNDED';
