ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_SUSPENDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ACCOUNT_RESTORED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FUND_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FUND_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RETAILER_DISPUTE_RESOLVED';
