import { and, eq, gt, gte, lt, ne, sum } from "drizzle-orm";
import { db, transaction } from "@repo/db";

import { AdminTableCard } from "@/components/admin/admin-table-card";
import { AdminEarningsTable } from "@/components/admin/earnings-table";
import { EarningsFilterBar } from "@/components/admin/earnings-filter-bar";
import { EarningsDownloadButton } from "@/components/admin/earnings-download-button";
import { StatCard } from "@/components/admin/stat-card";
import { fetchAdminEarnings } from "@/lib/admin-earnings-query";
import { formatInr } from "@/lib/format-money";
import { computePercentChange, getDayBounds } from "@/lib/stat-trend";

function pickSearchParams(
  resolved: { [key: string]: string | string[] | undefined },
) {
  return {
    status: resolved.status as string | undefined,
    operator: resolved.operator as string | undefined,
    search: resolved.search as string | undefined,
    dateFrom: resolved.dateFrom as string | undefined,
    dateTo: resolved.dateTo as string | undefined,
    sort: resolved.sort as string | undefined,
  };
}

export default async function AdminEarningsPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const resolvedParams = await searchParams;
  const query = pickSearchParams(resolvedParams);
  const { rows, status, sort } = await fetchAdminEarnings(query);

  const { todayStart, yesterdayStart } = getDayBounds();

  const successRechargeVolumeFilter = and(
    eq(transaction.status, "SUCCESS"),
    ne(transaction.operator, "MANUAL_CREDIT"),
  );

  const [
    [aggregate],
    [todayAggregate],
    [yesterdayAggregate],
    [totalVolumeRow],
    [todaysVolumeRow],
    [yesterdaysVolumeRow],
  ] = await Promise.all([
    db
      .select({ total: sum(transaction.adminCommission) })
      .from(transaction)
      .where(gt(transaction.adminCommission, 0)),
    db
      .select({ total: sum(transaction.adminCommission) })
      .from(transaction)
      .where(
        and(
          gt(transaction.adminCommission, 0),
          gte(transaction.createdAt, todayStart),
        ),
      ),
    db
      .select({ total: sum(transaction.adminCommission) })
      .from(transaction)
      .where(
        and(
          gt(transaction.adminCommission, 0),
          gte(transaction.createdAt, yesterdayStart),
          lt(transaction.createdAt, todayStart),
        ),
      ),
    db
      .select({ total: sum(transaction.amount) })
      .from(transaction)
      .where(successRechargeVolumeFilter),
    db
      .select({ total: sum(transaction.amount) })
      .from(transaction)
      .where(
        and(successRechargeVolumeFilter, gte(transaction.createdAt, todayStart)),
      ),
    db
      .select({ total: sum(transaction.amount) })
      .from(transaction)
      .where(
        and(
          successRechargeVolumeFilter,
          gte(transaction.createdAt, yesterdayStart),
          lt(transaction.createdAt, todayStart),
        ),
      ),
  ]);

  const totalEarnings = Number(aggregate?.total ?? 0);
  const todaysEarnings = Number(todayAggregate?.total ?? 0);
  const yesterdaysEarnings = Number(yesterdayAggregate?.total ?? 0);
  const totalVolume = Number(totalVolumeRow?.total ?? 0);
  const todaysVolume = Number(todaysVolumeRow?.total ?? 0);
  const yesterdaysVolume = Number(yesterdaysVolumeRow?.total ?? 0);
  const earningsThroughYesterday = totalEarnings - todaysEarnings;
  const volumeThroughYesterday = totalVolume - todaysVolume;
  const earningsTrend = computePercentChange(
    totalEarnings,
    earningsThroughYesterday,
  );
  const todaysEarningsTrend = computePercentChange(
    todaysEarnings,
    yesterdaysEarnings,
  );
  const volumeTrend = computePercentChange(totalVolume, volumeThroughYesterday);
  const todaysVolumeTrend = computePercentChange(todaysVolume, yesterdaysVolume);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          Platform earnings
        </h1>
        <p className="mt-1 text-sm text-muted">
          Track commission revenue generated by the platform.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          title="Total platform earnings"
          trendPercent={earningsTrend}
          value={formatInr(totalEarnings, { fractionDigits: 2 })}
        />
        <StatCard
          title="Today's earnings"
          trendPercent={todaysEarningsTrend}
          value={formatInr(todaysEarnings, { fractionDigits: 2 })}
        />
        <StatCard
          title="Total volume"
          trendPercent={volumeTrend}
          value={formatInr(totalVolume, { fractionDigits: 0 })}
        />
        <StatCard
          title="Today's volume"
          trendPercent={todaysVolumeTrend}
          value={formatInr(todaysVolume, { fractionDigits: 0 })}
        />
      </div>

      <EarningsFilterBar
        initialDateFrom={query.dateFrom || ""}
        initialDateTo={query.dateTo || ""}
        initialOperator={query.operator || "ALL"}
        initialSearch={query.search || ""}
        initialSort={sort}
        initialStatus={status}
      />

      <AdminTableCard
        description={
          rows.length > 0
            ? `Showing up to ${rows.length} matching transactions.`
            : "Adjust filters to find earning transactions."
        }
        headerAction={<EarningsDownloadButton data={rows} />}
        title="Earnings ledger"
      >
        <AdminEarningsTable rows={rows} />
      </AdminTableCard>
    </div>
  );
}
