import { and, eq, gt, gte, ne, sum } from "drizzle-orm";
import { Table } from "@heroui/react";
import { db, transaction } from "@repo/db";

import {
  AdminTableCard,
  AdminTableEmpty,
} from "@/components/admin/admin-table-card";
import { EarningsFilterBar } from "@/components/admin/earnings-filter-bar";
import { EarningsDownloadButton } from "@/components/admin/earnings-download-button";
import { Money } from "@/components/money";
import { StatCard } from "@/components/admin/stat-card";
import { fetchAdminEarnings } from "@/lib/admin-earnings-query";
import { formatInr } from "@/lib/format-money";
import { formatTableDateTime } from "@/lib/utils";
import { TransactionStatusChip } from "@/components/admin/transaction-status-chip";

function pickSearchParams(
  resolved: { [key: string]: string | string[] | undefined },
) {
  return {
    status: resolved.status as string | undefined,
    operator: resolved.operator as string | undefined,
    search: resolved.search as string | undefined,
    dateFrom: resolved.dateFrom as string | undefined,
    dateTo: resolved.dateTo as string | undefined,
    sort: resolved.sort as string | undefined,
  };
}

export default async function AdminEarningsPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const resolvedParams = await searchParams;
  const query = pickSearchParams(resolvedParams);
  const { rows, status, sort } = await fetchAdminEarnings(query);

  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  const successRechargeVolumeFilter = and(
    eq(transaction.status, "SUCCESS"),
    ne(transaction.operator, "MANUAL_CREDIT"),
  );

  const [
    [aggregate],
    [todayAggregate],
    [totalVolumeRow],
    [todaysVolumeRow],
  ] = await Promise.all([
    db
      .select({ total: sum(transaction.adminCommission) })
      .from(transaction)
      .where(gt(transaction.adminCommission, 0)),
    db
      .select({ total: sum(transaction.adminCommission) })
      .from(transaction)
      .where(
        and(
          gt(transaction.adminCommission, 0),
          gte(transaction.createdAt, todayStart),
        ),
      ),
    db
      .select({ total: sum(transaction.amount) })
      .from(transaction)
      .where(successRechargeVolumeFilter),
    db
      .select({ total: sum(transaction.amount) })
      .from(transaction)
      .where(
        and(successRechargeVolumeFilter, gte(transaction.createdAt, todayStart)),
      ),
  ]);

  const totalEarnings = Number(aggregate?.total ?? 0);
  const todaysEarnings = Number(todayAggregate?.total ?? 0);
  const totalVolume = Number(totalVolumeRow?.total ?? 0);
  const todaysVolume = Number(todaysVolumeRow?.total ?? 0);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          Platform earnings
        </h1>
        <p className="mt-1 text-sm text-muted">
          Track commission revenue generated by the platform.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          title="Total platform earnings"
          value={formatInr(totalEarnings, { fractionDigits: 2 })}
        />
        <StatCard
          title="Today's earnings"
          value={formatInr(todaysEarnings, { fractionDigits: 2 })}
        />
        <StatCard
          title="Total volume"
          value={formatInr(totalVolume, { fractionDigits: 0 })}
        />
        <StatCard
          title="Today's volume"
          value={formatInr(todaysVolume, { fractionDigits: 0 })}
        />
      </div>

      <EarningsFilterBar
        initialDateFrom={query.dateFrom || ""}
        initialDateTo={query.dateTo || ""}
        initialOperator={query.operator || "ALL"}
        initialSearch={query.search || ""}
        initialSort={sort}
        initialStatus={status}
      />

      <AdminTableCard
        description={
          rows.length > 0
            ? `Showing up to ${rows.length} matching transactions.`
            : "Adjust filters to find earning transactions."
        }
        headerAction={<EarningsDownloadButton data={rows} />}
        title="Earnings ledger"
      >
        {rows.length === 0 ? (
          <AdminTableEmpty message="No earnings match your filters." />
        ) : (
          <Table>
            <Table.ScrollContainer className="max-h-[min(70vh,720px)]">
              <Table.Content
                aria-label="Platform earnings"
                className="min-w-[800px]"
              >
                <Table.Header>
                  <Table.Column isRowHeader>Date & time</Table.Column>
                  <Table.Column>Retailer</Table.Column>
                  <Table.Column>Operator</Table.Column>
                  <Table.Column>Status</Table.Column>
                  <Table.Column className="text-right">Recharge amount</Table.Column>
                  <Table.Column className="text-right">Platform cut</Table.Column>
                </Table.Header>
                <Table.Body>
                  {rows.map((tx) => (
                    <Table.Row key={tx.id} className="whitespace-nowrap">
                      <Table.Cell className="whitespace-nowrap text-sm text-muted">
                        {formatTableDateTime(tx.createdAt)}
                      </Table.Cell>
                      <Table.Cell className="font-medium">{tx.user.name}</Table.Cell>
                      <Table.Cell>{tx.operator}</Table.Cell>
                      <Table.Cell>
                        <TransactionStatusChip status={tx.status} />
                      </Table.Cell>
                      <Table.Cell className="text-right">
                        <Money amount={tx.amount} fractionDigits={0} />
                      </Table.Cell>
                      <Table.Cell className="text-right font-semibold text-success">
                        <Money amount={tx.adminCommission} sign="+" />
                      </Table.Cell>
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table.Content>
            </Table.ScrollContainer>
          </Table>
        )}
      </AdminTableCard>
    </div>
  );
}
