import { desc, eq, gt, sum } from "drizzle-orm";
import { Landmark } from "lucide-react";
import { Table } from "@heroui/react";
import { db, transaction, user } from "@repo/db";

import {
  AdminTableCard,
  AdminTableEmpty,
} from "@/components/admin/admin-table-card";
import {
  EarningsDownloadButton,
  type AdminEarningRow,
} from "@/components/admin/earnings-download-button";
import { StatCard } from "@/components/admin/stat-card";

function formatInr(amount: number, fractionDigits = 2): string {
  return `₹${amount.toLocaleString("en-IN", {
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
  })}`;
}

export default async function AdminEarningsPage() {
  const transactions = await db
    .select({
      id: transaction.id,
      createdAt: transaction.createdAt,
      amount: transaction.amount,
      status: transaction.status,
      operator: transaction.operator,
      adminCommission: transaction.adminCommission,
      userName: user.name,
      userEmail: user.email,
    })
    .from(transaction)
    .innerJoin(user, eq(transaction.userId, user.id))
    .where(gt(transaction.adminCommission, 0))
    .orderBy(desc(transaction.createdAt))
    .limit(50);

  const [aggregate] = await db
    .select({ total: sum(transaction.adminCommission) })
    .from(transaction)
    .where(gt(transaction.adminCommission, 0));

  const totalEarnings = Number(aggregate?.total ?? 0);

  const rows: AdminEarningRow[] = transactions.map((tx) => ({
    id: tx.id,
    createdAt: tx.createdAt.toISOString(),
    amount: tx.amount,
    status: tx.status,
    operator: tx.operator,
    adminCommission: tx.adminCommission,
    user: { name: tx.userName, email: tx.userEmail },
  }));

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          Platform earnings
        </h1>
        <p className="mt-1 text-sm text-muted">
          Track commission revenue generated by the platform.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <StatCard
          description="Accumulated from all transactions"
          icon={Landmark}
          title="Total platform earnings"
          value={formatInr(totalEarnings)}
        />
      </div>

      <AdminTableCard
        description="The last 50 transactions that generated platform revenue."
        headerAction={<EarningsDownloadButton data={rows} />}
        title="Recent earnings ledger"
      >
        {rows.length === 0 ? (
          <AdminTableEmpty message="No earnings recorded yet." />
        ) : (
          <Table>
            <Table.ScrollContainer>
              <Table.Content
                aria-label="Recent platform earnings"
                className="min-w-[720px]"
              >
                <Table.Header>
                  <Table.Column isRowHeader>Date & time</Table.Column>
                  <Table.Column>Retailer</Table.Column>
                  <Table.Column>Operator</Table.Column>
                  <Table.Column className="text-right">Recharge amt</Table.Column>
                  <Table.Column className="text-right">Platform cut</Table.Column>
                </Table.Header>
                <Table.Body>
                  {rows.map((tx) => (
                    <Table.Row key={tx.id}>
                      <Table.Cell>
                        <div className="flex flex-col text-sm">
                          <span className="text-foreground">
                            {new Date(tx.createdAt).toLocaleDateString("en-IN")}
                          </span>
                          <span className="text-xs text-muted">
                            {new Date(tx.createdAt).toLocaleTimeString("en-IN", {
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </span>
                        </div>
                      </Table.Cell>
                      <Table.Cell className="font-medium">{tx.user.name}</Table.Cell>
                      <Table.Cell>{tx.operator}</Table.Cell>
                      <Table.Cell className="text-right font-mono text-sm text-muted">
                        {formatInr(tx.amount, 0)}
                      </Table.Cell>
                      <Table.Cell className="text-right font-semibold text-success">
                        +{formatInr(tx.adminCommission)}
                      </Table.Cell>
                    </Table.Row>
                  ))}
                </Table.Body>
              </Table.Content>
            </Table.ScrollContainer>
          </Table>
        )}
      </AdminTableCard>
    </div>
  );
}
